name: Sam Kavanagh, Developer
permalink: /blog/:year/:month/:day/:title

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  tutorials:
    output: true
  workshops:
    output: true
plugins:
  - jemoji

baseurl: /teaching
